---
  - name: "Profile: Create all required folders"
    file:
      path: "{{ item.path }}"
      state: directory
    with_items: "{{ folders }}"
  
  - name: "Profile: Clone all required git repos"
    git:
      repo: "{{ item.repo }}"
      dest: "{{ item.dest }}"
    with_items: "{{ git_repos }}"
  
  - name: "Profile: Configure VS Code"
    command: code --install-extension {{ item.extension }}
    with_items: "{{ vscode_extension }}"
  #
  # Dotfiles
  #
  - name: "Profile: Check if git directory Dotfiles is cloned"
    stat:
      path: ~/git/clnrmn/dotfiles/
    register: dotfiles

  - name: "Profile: Sync Dotfiles"
    synchronize:
      src: "~/git/clnrmn/dotfiles/"
      dest: "~"
      checksum: yes
      rsync_opts:
      - "--exclude=.git"
    when: dotfiles.stat.exists

  #
  # VIM Setup
  #
  - name: "Profile: Check if .vimrc exists"
    stat:
      path: "~/.vimrc"
    register: vimrc
  - name: "Profile: Install vim Plugins"
    command: vim +PluginInstall +qall
    when: vimrc.stat.exists

  #
  # Tilix Setup
  #
  - name: "Profile: Check if tilix is installed"
    stat:
      path: /usr/bin/tilix
    register: tilix
  - name: "Profile: Check if links is already created"
    stat:
      path: /usr/bin/gnome-terminal
    register: gnometerminal
  - name: "Profile: Create a copy of /usr/bin/gnome-terminal"
    copy:
      src: /usr/bin/gnome-terminal
      dest: /usr/bin/gnome-terminal-bak
    become: true
    when: not gnometerminal.stat.islnk and tilix.stat.exists
  - name: "Profile: Remove /usr/bin/gnome-terminal"
    file:
      path: /usr/bin/gnome-terminal
      state: absent
    become: true
    when: not gnometerminal.stat.islnk and tilix.stat.exists
  - name: "Profile: Create a symbolic link"
    file:
      src:  /usr/bin/tilix
      dest: /usr/bin/gnome-terminal
      state: link
    become: true
    when: tilix.stat.exists and not gnometerminal.stat.islnk
    
  
